/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.BairroController;
import Controller.CidadeController;
import Controller.EstadoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Bairro;
import model.Cidade;
import model.Estado;

/**
 *
 * @author Artom
 */
public class TelaCadBairro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadBairro
     */
    public TelaCadBairro() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        jlBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jlCidade = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox();
        jlEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cdastro de Bairro");

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jlBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlBairro.setText("Bairro:");

        jlCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCidade.setText("Cidade:");

        jlEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlEstado.setText("Estado:");

        cbxEstado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbxEstadoComponentShown(evt);
            }
        });
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBairro)
                    .addComponent(jlEstado)
                    .addComponent(jlCidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCidade))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método que preenche o combo com as cidades listadas no banco
    private void preencherCombo(){
        try {
            ArrayList<Estado> est = new ArrayList<>();
            EstadoController ec = new EstadoController();

            est = ec.buscarEstados();

            for (int i = 0; i < est.size(); i++) {
                cbxEstado.addItem(est.get(i));
            }//Fecha for

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao preencher combo box de estados!"
                    + e.getMessage());
        }//Fecha cacth
    }//Fecha método
    
     //Método que lista as cidades da uf selecionada na combo box de estado
    private void preencherComboCidade() {
        try {
            ArrayList<Cidade> cid = new ArrayList<>();
            CidadeController cc = new CidadeController();

            Cidade c = new Cidade();
            c.setEstado((Estado) cbxEstado.getSelectedItem());

            String query = "where idestado = " + c.getEstado().getIdEstado();

            cid = cc.filtrarCidade(query);

            for (int i = 0; i < cid.size(); i++) {
                cbxCidade.addItem(cid.get(i));
            }//Fecha for

        } catch (Exception e) {

        }//Fecha catch
    }//Fecha método
    
    //Método que limpa os campos
    private void limparCampos(){
        txtBairro.setText(null);
        cbxEstado.setSelectedIndex(0);
    }//Fecha método
       
    //Método responsável por cadastrar o bairro no banco
    private void cadastrar(){
        try {
            Bairro b = new Bairro();
            
            b.setNome(txtBairro.getText());
            b.setCidade((Cidade)cbxCidade.getSelectedItem());
            
            BairroController bc = new BairroController();
            
            bc.cadastrar(b);
            
            JOptionPane.showMessageDialog(rootPane, 
                    "Bairro cadastrado com sucesso!");
            
            limparCampos();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao cadastrar bairro " + e.getMessage());
        }//Fecha cacth
    }//Fecha método
    
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        cbxCidade.removeAllItems();
        preencherComboCidade();
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void cbxEstadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbxEstadoComponentShown
        cbxCidade.removeAllItems();
        preencherComboCidade();
    }//GEN-LAST:event_cbxEstadoComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cbxCidade;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JTextField txtBairro;
    // End of variables declaration//GEN-END:variables
}
