/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Controller.ClienteController;
import Controller.UsuarioController;
import javax.swing.JOptionPane;


/**
 *
 * @author Artom
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
   
    //Método que chama a telaUsuario
    private void abrirTelaUsuario(){
        TelaUsuario form = new TelaUsuario();
        form.setVisible(true);
        jDesktop.add(form);
    }//Fecha método
    
    //Método para abrir a tela de clientes
    private void abrirTelaCliente(){
        TelaCliente form = new TelaCliente();
        form.setVisible(true);
        jDesktop.add(form);
    }//Fecha método
    
    //Método que chama a tela de cadastro de estado
    private void abrirCadEstado(){
        TelaCadEstado form = new TelaCadEstado();
        form.setVisible(true);
        jDesktop.add(form);
    }//Fecha método
    
    //Método que chama a tela de cadastro de cidade
    private void abrirCadCidade(){
        TelaCadCidade form = new TelaCadCidade();
        form.setVisible(true);
        jDesktop.add(form);
    }//Fecha método
    
    //Método que chama a tela de cadastro de bairro
    private void abrirCadBairro(){
        TelaCadBairro form = new TelaCadBairro();
        form.setVisible(true);
        jDesktop.add(form);
    }//Fecha método
    
    
    //Método que exibi o relatório de usuários
    private void relatorioUsuario(){
        int op = JOptionPane.showConfirmDialog(rootPane, "Imprir relatório?",
        "Atenção", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION){
            
            try {
                UsuarioController uc = new UsuarioController();
                uc.imprirmirRelatorio();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,
                        "Erro!" + e.getMessage());
            }//Fecha catch
        }//Fecha if
    }//Fecha método
    
     //Método que exibi o relatório de clientes
    private void relatorioCliente(){
        int op = JOptionPane.showConfirmDialog(rootPane, "Imprir relatório?",
        "Atenção", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION){
            
            try {
                ClienteController cc = new ClienteController();
                cc.imprimirRelatorio();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,
                        "Erro!" + e.getMessage());
            }//Fecha catch
        }//Fecha if
    }//Fecha método

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuManutencao = new javax.swing.JMenu();
        menuItemBairro = new javax.swing.JMenuItem();
        menuItemCidade = new javax.swing.JMenuItem();
        menuItemEstado = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatorioClientes = new javax.swing.JMenuItem();
        menuRelatorioUsuarios = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItem1);

        menuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuItemUsuario.setText("Usuário");
        menuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemUsuario);

        jMenuBar1.add(menuCadastro);

        menuManutencao.setText("Manutenção");
        menuManutencao.setFocusable(false);

        menuItemBairro.setText("Bairro");
        menuItemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBairroActionPerformed(evt);
            }
        });
        menuManutencao.add(menuItemBairro);

        menuItemCidade.setText("Cidade");
        menuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCidadeActionPerformed(evt);
            }
        });
        menuManutencao.add(menuItemCidade);

        menuItemEstado.setText("Estado");
        menuItemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEstadoActionPerformed(evt);
            }
        });
        menuManutencao.add(menuItemEstado);

        jMenuBar1.add(menuManutencao);

        menuRelatorios.setText("Relatórios");

        menuRelatorioClientes.setText("Clientes");
        menuRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatorioClientes);

        menuRelatorioUsuarios.setText("Usuários");
        menuRelatorioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioUsuariosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatorioUsuarios);

        jMenuBar1.add(menuRelatorios);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        setSize(new java.awt.Dimension(816, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuarioActionPerformed
        abrirTelaUsuario();
    }//GEN-LAST:event_menuItemUsuarioActionPerformed

    private void menuRelatorioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioUsuariosActionPerformed
        relatorioUsuario();
    }//GEN-LAST:event_menuRelatorioUsuariosActionPerformed

    private void menuItemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBairroActionPerformed
        abrirCadBairro();
    }//GEN-LAST:event_menuItemBairroActionPerformed

    private void menuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCidadeActionPerformed
       abrirCadCidade();
    }//GEN-LAST:event_menuItemCidadeActionPerformed

    private void menuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEstadoActionPerformed
        abrirCadEstado();
    }//GEN-LAST:event_menuItemEstadoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abrirTelaCliente();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioClientesActionPerformed
        relatorioCliente();
    }//GEN-LAST:event_menuRelatorioClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemBairro;
    private javax.swing.JMenuItem menuItemCidade;
    private javax.swing.JMenuItem menuItemEstado;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenu menuManutencao;
    private javax.swing.JMenuItem menuRelatorioClientes;
    private javax.swing.JMenuItem menuRelatorioUsuarios;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
