/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.CidadeController;
import Controller.EstadoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cidade;
import model.Estado;

/**
 *
 * @author Artom
 */
public class TelaCadCidade extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadCidade
     */
    public TelaCadCidade() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Cidade");

        jlCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCidade.setText("Cidade:");

        jlEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlEstado.setText("Estado:");

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCidade)
                        .addGap(18, 18, 18)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlEstado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método responsável por preencher o combo box com os dados dos estados
    private void preencherCombo(){
        try {
            ArrayList<Estado> est = new ArrayList<>();
            EstadoController ec = new EstadoController();
            
            est = ec.buscarEstados();
            
            for(int i = 0; i < est.size(); i++){
                cbxEstado.addItem(est.get(i));
            }//Fecha for
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro! " + e.getMessage());
        }//Fecha cacth
    }//Fecha método

    //Método para limpar o campo cidade e resetar o combo box
    private void limparCampos(){
        txtCidade.setText(null);
        cbxEstado.setSelectedIndex(0);
    }//Fecha método
    
    //Método para cadastrar cidade incluindo o id do estado
    private void cadastrar(){
        try{
            Cidade c = new Cidade();
            
            c.setNome(txtCidade.getText());
            c.setEstado((Estado)cbxEstado.getSelectedItem());
            
            CidadeController cc = new CidadeController();
            cc.cadastrar(c);
            
            JOptionPane.showMessageDialog(rootPane, 
                    "Cidade cadastrada com sucesso!");
            
            limparCampos();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Erro! " + e.getMessage());
        }//Fecha cacth
    }//Fecha método
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables
}
