/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.EstadoController;
import javax.swing.JOptionPane;
import model.Estado;
import model.Validacao;

/**
 *
 * @author Artom
 */
public class TelaCadEstado extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadEstado
     */
    public TelaCadEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jlSigla = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Estado");

        jlEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlEstado.setText("Estado:");

        jlSigla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlSigla.setText("Sigla:");

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEstado)
                    .addComponent(jlSigla))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSigla)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(350, 200));
    }// </editor-fold>//GEN-END:initComponents

    //Método que válida os campos digitados
    private boolean validarCampos() {
        if (!(Validacao.validarEstado(txtEstado.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Nome de estado inválido");
            txtEstado.requestFocus();
            return false;
        }//Fecha if
        if (!(Validacao.validarSigla(txtSigla.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Sigla inválida");
            txtSigla.requestFocus();
            return false;
        }//Fecha if

        return true;

    }//Fecha método

    //Método para cadastrar os dados digitados na tabela estado
    private void cadastrar() {
        try {
            if (validarCampos()) {
                Estado e = new Estado();

                e.setNome(txtEstado.getText());
                e.setSigla(txtSigla.getText());

                EstadoController ec = new EstadoController();
                ec.cadastrar(e);

                JOptionPane.showMessageDialog(rootPane,
                        "Estado cadastrado com sucesso!");

                limparCampos();
            }//Fecha if

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao cadastrar estado!" + e.getMessage());
        }//Fecha catch
    }//Fecha método

    //Método para limpar os campos de texto 
    private void limparCampos() {
        txtEstado.setText(null);
        txtSigla.setText(null);
    }//Fecha método

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlSigla;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
