/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Artom
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadProjeto = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmiConsultaProjeto = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout jAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jAreaDeTrabalho);
        jAreaDeTrabalho.setLayout(jAreaDeTrabalhoLayout);
        jAreaDeTrabalhoLayout.setHorizontalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jAreaDeTrabalhoLayout.setVerticalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");

        jmiCadProjeto.setText("Projeto");
        jmiCadProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProjetoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadProjeto);

        jMenuBar.add(jmCadastro);

        jmConsulta.setText("Consulta");

        jmiConsultaProjeto.setText("Projeto");
        jmiConsultaProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaProjetoActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiConsultaProjeto);

        jMenuBar.add(jmConsulta);

        jmSair.setText("Sair");
        jmSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmSairKeyPressed(evt);
            }
        });
        jMenuBar.add(jmSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho)
        );

        setSize(new java.awt.Dimension(816, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadProjeto(){
        UICadProjeto uicp = new UICadProjeto();
        jAreaDeTrabalho.add(uicp);
        uicp.setVisible(true);
    }
    
    private void abrirUIProjeto(){
        UIProjeto uip = new UIProjeto();
        jAreaDeTrabalho.add(uip);
        uip.setVisible(true);
    }
    
    private void jmiCadProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProjetoActionPerformed
        abrirCadProjeto();
    }//GEN-LAST:event_jmiCadProjetoActionPerformed

    private void jmiConsultaProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaProjetoActionPerformed
        abrirUIProjeto();
    }//GEN-LAST:event_jmiConsultaProjetoActionPerformed

    private void jmSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmSairKeyPressed
        System.exit(0);
    }//GEN-LAST:event_jmSairKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaDeTrabalho;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadProjeto;
    private javax.swing.JMenuItem jmiConsultaProjeto;
    // End of variables declaration//GEN-END:variables
}
