/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProjetoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.Projeto;

/**
 *
 * @author Artom
 */
public class UIProjeto extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "Descrição", "Prazo",
                "Data início", "Data fim", "Status"});
    
    /**
     * Creates new form UIProjeto
     */
    public UIProjeto() {
        initComponents();
        preencherTabela();
        gerarMaskara();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgStatus = new javax.swing.ButtonGroup();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jtPesq = new javax.swing.JTextField();
        jcomboFiltro = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjeto = new javax.swing.JTable();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jlPrazo = new javax.swing.JLabel();
        jftPrazo = new javax.swing.JFormattedTextField();
        jlDataInicio = new javax.swing.JLabel();
        jftDataInicio = new javax.swing.JFormattedTextField();
        jlDataFim = new javax.swing.JLabel();
        jftDataFim = new javax.swing.JFormattedTextField();
        jlStatus = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jrAndamento = new javax.swing.JRadioButton();
        jrConcluido = new javax.swing.JRadioButton();
        jrCancelado = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbPreencher = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbConfirmarAlteracao = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Status" }));
        jcomboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFiltroItemStateChanged(evt);
            }
        });

        jLayeredPane3.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jcomboFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProjeto.getTableHeader().setReorderingAllowed(false);
        tblProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjetoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProjeto);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlNome.setText("Nome:");

        jlDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlDesc.setText("Descrição:");

        jtaDesc.setColumns(20);
        jtaDesc.setRows(5);
        jScrollPane2.setViewportView(jtaDesc);

        jlCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCodigo.setText("Código:");

        jtCodigo.setEditable(false);
        jtCodigo.setEnabled(false);

        jlPrazo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlPrazo.setText("Prazo:");

        jlDataInicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlDataInicio.setText("Data inicio:");

        jlDataFim.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlDataFim.setText("Data fim:");

        jlStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlStatus.setText("Status:");

        jLayeredPane5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bgStatus.add(jrAndamento);
        jrAndamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrAndamento.setText("Em Andamento");
        jrAndamento.setActionCommand("Em andamento");

        bgStatus.add(jrConcluido);
        jrConcluido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrConcluido.setText("Concluído");
        jrConcluido.setActionCommand("Concluído");

        bgStatus.add(jrCancelado);
        jrCancelado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrCancelado.setText("Cancelado");
        jrCancelado.setActionCommand("Cancelado");

        jLayeredPane5.setLayer(jrAndamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jrConcluido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jrCancelado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrAndamento)
                    .addComponent(jrConcluido)
                    .addComponent(jrCancelado))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrAndamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrConcluido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrCancelado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlDesc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlPrazo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jftPrazo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlDataInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jftDataInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlDataFim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jftDataFim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDesc)
                    .addComponent(jlNome))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtNome)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlCodigo)
                        .addGap(28, 28, 28)
                        .addComponent(jtCodigo))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlPrazo)
                        .addGap(37, 37, 37)
                        .addComponent(jftPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlDataFim)
                        .addGap(22, 22, 22)
                        .addComponent(jftDataFim))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlDataInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlStatus)
                        .addGap(57, 57, 57)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDesc)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCodigo)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPrazo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDataInicio)
                            .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDataFim)
                            .addComponent(jftDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencher.setText("Preencher");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbConfirmarAlteracao.setText("Confirmar Alteração");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbConfirmarAlteracao)
                .addGap(91, 91, 91))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfirmarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * Método responsável por gerar a maskara dos campos prazo, 
    * dataInicio e dataFim.
    */
    private void gerarMaskara(){
        try{
            MaskFormatter data = new MaskFormatter("##/##/####");
            jftPrazo.setFormatterFactory(new DefaultFormatterFactory(data));
            jftDataInicio.setFormatterFactory(new DefaultFormatterFactory(data));
            jftDataFim.setFormatterFactory(new DefaultFormatterFactory(data));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro na maskara" + e.getMessage());
        }
    }
    
    //Método que faz o preenchimento da tabela e sua atualização
    private void preencherTabela(){
        try{
            ProjetoController pc = new ProjetoController();
            ArrayList<Projeto> proj = new ArrayList<>();
            proj = pc.buscarProjeto();
            
            for(int i = 0; i < proj.size(); i++){
                dtm.addRow(new String[]{
                    String.valueOf(proj.get(i).getId()),
                    proj.get(i).getNome(),
                    proj.get(i).getDescricao(),
                    proj.get(i).getPrazo(),
                    proj.get(i).getDataInicio(),
                    proj.get(i).getDataFim(),
                    proj.get(i).getStatus()  
                });
                
                tblProjeto.setModel(dtm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao buscar dados do banco" + e.getMessage());
        }
    }
    
    //Método responsável por limpar a tabela 
    private void limparTabela(){
        dtm.setNumRows(0);
    }
    
    //Método responsável por limpar os campos de texto
    private void limparCampos(){
        jtCodigo.setText(null);
        jtNome.setText(null);
        jtaDesc.setText(null);
        jftPrazo.setText(null);
        jftDataInicio.setText(null);
        jftDataFim.setText(null);
        bgStatus.clearSelection();
        gerarMaskara();
    }
    
    
    /**
     * Método responsável por setar os dados da linha selecionada
     * nos campos de texto
     */
    private void alterar(){
        int linha = tblProjeto.getSelectedRow();
        if(linha != -1){
            jtCodigo.setText((String)tblProjeto.getValueAt(linha, 0));
            jtNome.setText((String)tblProjeto.getValueAt(linha, 1));
            jtaDesc.setText((String)tblProjeto.getValueAt(linha, 2));
            jftPrazo.setText((String)tblProjeto.getValueAt(linha, 3));
            jftDataInicio.setText((String)tblProjeto.getValueAt(linha, 4));
            jftDataFim.setText((String)tblProjeto.getValueAt(linha, 5));
            if(tblProjeto.getValueAt(linha, 6).equals("Em andamento")){
                jrAndamento.setSelected(true);
            }else if(tblProjeto.getValueAt(linha, 6).equals("Concluído")){
                jrConcluido.setSelected(true);
            }else{
                jrCancelado.setSelected(true);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione um linha!");
        }
    }
    
    //Método que confirma a alteração de dados no banco
    private void confirmarAlteracao(){
        try {
            Projeto p = new Projeto();
            p.setId(Long.parseLong(jtCodigo.getText()));
            p.setNome(jtNome.getText());
            p.setDescricao(jtaDesc.getText());
            p.setPrazo(jftPrazo.getText());
            p.setDataInicio(jftDataInicio.getText());
            p.setDataFim(jftDataFim.getText());
            p.setStatus(bgStatus.getSelection().getActionCommand());
            
            ProjetoController pc = new ProjetoController();
            pc.alterarProjeto(p);
            
            JOptionPane.showMessageDialog(rootPane, 
                    "Projeto alterado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao alterar projeto" + e.getMessage());
        }
    }
    
    //Método que deleta a linha da tabela selecionada do banco de dados
    private void deletar(){
        try {
            int linha = tblProjeto.getSelectedRow();
            if(linha == -1){
                JOptionPane.showMessageDialog(rootPane, 
                        "Selecione uma linha na tabela");
            }else{
                int op = JOptionPane.showOptionDialog(null,
                "Confirma a exclusão?",
                "Pergunta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,
                new String[]{"Sim", "Não"}, "Sim");
                if(op == 0){
                    ProjetoController pc = new ProjetoController();
                    String id = tblProjeto.getValueAt(linha, 0).toString();
                    pc.deletarProjeto(Long.parseLong(id));
                    
                    JOptionPane.showMessageDialog(rootPane, 
                            "Projeto excluído com sucesso");
                }   
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao excluir projeto " + e.getMessage());
        }
    }
    
    //Método capaz de filtrar dados no banco
    private void filtrar(){
        try {
            if(jtPesq.getText().isEmpty()){
                limparTabela();
                preencherTabela();
            }else{
                String filtro = jcomboFiltro.getSelectedItem().toString();
                String pesq = jtPesq.getText();
                String query = "";
                if(filtro.equalsIgnoreCase("Nome")){
                    query = "where nome like '%" + pesq + "%'";
                }else if(filtro.equalsIgnoreCase("Código")){
                    query = "where id = " + pesq;
                }else if(filtro.equalsIgnoreCase("Status")){
                    query = "where status like '%" + pesq + "%'";
                }
                
                ProjetoController pc = new ProjetoController();
                ArrayList<Projeto> proj = new ArrayList<>();
                
                proj = pc.filtrar(query);
                
                for(int i = 0; i < proj.size(); i++){
                    dtm.addRow(new String[]{
                        String.valueOf(proj.get(i).getId()),
                        String.valueOf(proj.get(i).getNome()),
                        String.valueOf(proj.get(i).getDescricao()),
                        String.valueOf(proj.get(i).getPrazo()),
                        String.valueOf(proj.get(i).getDataInicio()),
                        String.valueOf(proj.get(i).getDataFim()),
                        String.valueOf(proj.get(i).getStatus())
                    });
                }
                
                tblProjeto.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao filtrar dados" + e.getMessage());
        }
    }
        
    
    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jcomboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFiltroItemStateChanged
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jcomboFiltroItemStateChanged

    private void tblProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjetoMouseClicked
        alterar();
    }//GEN-LAST:event_tblProjetoMouseClicked

    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
        limparCampos();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
        limparCampos();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JComboBox<String> jcomboFiltro;
    private javax.swing.JFormattedTextField jftDataFim;
    private javax.swing.JFormattedTextField jftDataInicio;
    private javax.swing.JFormattedTextField jftPrazo;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDataFim;
    private javax.swing.JLabel jlDataInicio;
    private javax.swing.JLabel jlDesc;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPrazo;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JRadioButton jrAndamento;
    private javax.swing.JRadioButton jrCancelado;
    private javax.swing.JRadioButton jrConcluido;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextArea jtaDesc;
    private javax.swing.JTable tblProjeto;
    // End of variables declaration//GEN-END:variables
}
